### ISSUE TITLE
Compiler version

### ISSUE THREAD

**Issue by LarsWiegers** [ladiesman6969/streampi_client#1]
Hi i am getting errors using the 1.8 compiler. What compiler are you using for building?

Cool project!

**Comment by ladiesman6969** [comment]
@LarsWiegers Hi! This project was entirely written for java 9+ so that it can run on JavaFX 11, as JavaFX 8 on Embedded had serious issues, which were addressed by javafx 11. I personally used Liberica 11 JDK by BellSoft (https://bell-sw.com/), which comes prebundled with javafx.

**Comment by ladiesman6969** [comment]
if you face any issues with JDK 9+ compiler, open another issue ;) I'll be ready to help.
