### ISSUE TITLE
Meta and arrow keys don't work on linux

### ISSUE THREAD

**Issue by koschie** [ladiesman6969/streampi_client#10]
I'm setup on rpi as the client and manjaro as server.
When i create a new hot key, the keyboard recoder does not recognize the arrow keys at all, and the meta key is read as "WINDOWS" and has no effect on the OS. 
I tried changing the key name in ~/actions/details action file to "SUPER", "META" to no effect. Any help would be appreciated.

**Comment by dubbadhar** [comment]
fix income in 1.0

**Comment by dubbadhar** [comment]
fix incoming in 1.0!
