### ISSUE TITLE
Can't install stream-pi on any device syntax error near unexpected token `<'

### ISSUE THREAD

**Issue by HexLions** [ladiesman6969/streampi_client#120]
Today i have try to install stream pi but when i paste "curl -sSL https://install.stream-pi.com/client/raspberry-pi | bash" this error appear

bash: line 1: syntax error near unexpected token `<'
bash: line 1: `<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="/cdn-cgi/styles/challenges.css" rel="stylesheet"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span class="icon-wrapper"><div class="heading-icon warning-icon"></div></span><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '2',cZone: 'install.stream-pi.com',cType: 'managed',cNounce: '24007',cRay: '7f28799f4bf71227',cHash: '3fc2045b14d3fd8',cUPMDTk: "\/client\/raspberry-pi?__cf_chl_tk=yrAdWPgKjnx7BU8qGlRGnYRvk3GsN6jTp1..FnY5.K8-1691337441-0-gaNycGzNCrs",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '0',cTplV: 5,cTplB: 'cf',cK: "",fa: "/client/raspberry-pi?__cf_chl_f_tk=yrAdWPgKjnx7BU8qGlRGnYRvk3GsN6jTp1..FnY5.K8-1691337441-0-gaNycGzNCrs",md: "0MC8.PdaqydE78rjLH6f.FX5jHPzaXs_weyGPw2D7Fk-1691337441-0-Ac9lD46-OgPUe1-eg5xi6mcfK35S-wLsVo47yh3AMcD-vasXo0MOZ7BjE5gn03bHG12iCZoPg0zk6KW2B1lMYOYIr77fu-mD4I2LLUylJwdEjlIt041ypV7Qu94hsNx0TzIohGi-Yf2QEEjvLYIsPX_7tEusoj-O0dKfn0B0Hl58uIGqDEsBGyiNCOKvYSOjcjBYQEdMIkpemAfq6f7Ty8M4-gj13gcnuidgBktRNd-N9bd5aL-kY-4P1ZG07LuTX7ZKxY7c10orMUPDvumr44aICd6S-jeY7w7Qg93VVJ7PDHcn6EBZaWos5z4Nxjy-IQtcNEFjVwP-cY_xM4DsqqNbZl9GOo0rmrBxglJatlaeIhveMu1Pycf-j4pgtO2nTYFX4ueRf9QiHnZvjjHTVyRXtbpO3CmgItQg9kg0IIShfTbilYsske5YfnqCfXwp6dz8D5ifYHDQYvPPjidguAO1USiPG_eBxDCc8JV7X41Pt9nzC00klbOi8uH6mQ9r31T7sfXk7JT5dO2vPnwe36C-UMgXbiGwKKoZSUDBfFX_g-yZjvliB_Vy2To8twcg6i9uoVr3nwettgX_7yDrcWRFpdsU96RMwFGOO3qFngyWW4TZj5K0-xnCykepL3lQru8D0DM6IQRj6y152xg3yUTgPjwl7IbXP1d_AaLT5hEFCydAeLbynmBO5ND6a9LcUsrYoVua1T2RAb7WUDyrxmIFwOZ7AgGDDjFgAMizCNvUwf4PlBgs2Jw7Hcrw3tf1F-JKJA4nyjLSbMTGTHRaS5oCK6q4IXdXN7PvMAdGbTnnFmGmDUV30XBm9DDSV8cFHnPy2_VsdhpXw0OWJA5rhRnj1fEsEJCQnaH977BBuAdGuN7iIXgzvr-JtmpzUaS-hH_w0g-iDSF3l4P33yU0mnwwikWGld8gqjce9HSM6csbfuOzlkN3fxkFTyrvl7bR8VehosysXgzEAVvKTxCYVoyVD4rElo2IrqJ15gEAy4ZvFog7zlFY8iDQMn3CHAq6JEwvH2eOXEpfMrjsFkCMhRXFjhDg3BAgo5zp7ZRHPlXv6K7TwdU0jPnQo9vjqdvyK4sycMzLfif_uHvDzrt7fmntTPInVRwHstX8zjeOak5QPtB1O9fUxr3_wkb6n28PWLYDdh05h2M_hpvuJcfSpER3JhZjLawhap1vaQfKFDXoR275KHCY9Y7Kx4_djBUeffhvA7UuuQQolgaYxKm0MmruP8RqjJzhMT9Bfx-XS4N_Qk_BXKXjyj2ZTBRIBSpnMEH9s8ofOM1f52KJ-Kx5YkuReamuAzEmbHT3jF-KzWvLGePRhYBir8jMU-lM3nQ0i84k6kpByvxcS4pG-C5RZcd-ZyUN3k-l7ufsNkxay7JZZO_xEsNNxopWmf2OhXrzURlsjgr0FMsWU91-hrENkz6iHhB1vuN3IdZfMBIG8JIY41lvWtcDCDzvsOzQHME530MxSYVtCol2ZF8gjXtosKbSRO0rm4NSnN7T7lxTpv4Mt7KwxK1keiqX2vHppMP2AzLVSdCU1zJJ62Xr92UpyP-jazMVf5g_nU0X-eVwpXqey3Vj5cd_Ze1sMXj5Pc-Wmcg3s_RTNeRFNUZlv7_kYMHP6RLOxNe8lalfvO6RXayV8QAFO0vgfl6vqNjz4eRB0rYhvd4NN86PoLJm_QrloQhEv1iuSl8BfIT0oukzierHlmK4fC0X4fQIoEp89ZIXt_oLnphv6AQisaorNLCOieZnnCsZHitr9zXZhZmCRidWPgK1HHJX2kcHmtR7IyElaM0jSA7NkRGyi3qwyVZPLAgh0Xh89zwduQwWSVkPPzAFtVglgEvPqh09ziWx7mvxxr180lhv9chPVPhRL_tkgYmM2x6p_mBm_K7PuW5lqVpY0JpxkdHAu8z8ovnoAOIeUNRXOATB3NOnPIghFORi8W5VT9blUB-TPsrnROevHmBVBVHsOMNvxqXD3HAmfho6-MJNaUAv5y3wn-fabgFzKXKxJZR5IvLtxNs1u1feh2ofkF3DXK0mHm0HjwP1RHVjHaSvMR_B_aGgzv-H8ddFE2wKXy0vbW8VtmcSNV3pVpD4it0ON8ftVCuBv_7ogsL9HybhvNWsBtFKkUITqI9FHgQbsM6Pw2sFHov3Ok851hfrbz-FyaWHk7EotaH6fsxVeNEwmktCpSrOhWjJ065nZZ4_fdfBDN9HHk8WiOn9WF4NvDBnr6QibT-whd3UagHo_W63oFSdcH5CW76OvSaqjNWR1LQgEjjseI4KEQTOJYSfi99D5JnbfNzJoC-ORhR-ZxH254zh3sXeE9FJIgXFu6WbELrXjIHOIBQGtdfmPxzvJeza3A_ba7tlo8qrQkPBwRDLAQv9kBwwaYtFA_bI74cI0OKriUcrHnUdVs2jE3MWpc3Xx7EY0Hrv5HGDY_AIVkqOK0AxYsPJyW0_Rmv5l31DgGko0-EdlbuWAiPELib7sFlxnSs6tiQb2VSDXWd1QeTMC8mxTdgBkQ9zZyYjTKf_cQzQqiYKM3aTOYSLl2xE2RuT_TdA5B113iGQB0DuvIyWfiklyjFwRUNo8AaaX41WUH3SzrhUunm2BybHwLq3tEse6Lbu7TNluM8Wi_FIXOGbaD6jlT6HjyQpDnm5-bxrV8p4tziNtatVW8kYsUUm2KBJdmv-Dyq407QBrlf2uA",cRq: {ru: 'aHR0cHM6Ly9pbnN0YWxsLnN0cmVhbS1waS5jb20vY2xpZW50L3Jhc3BiZXJyeS1waQ==',ra: 'Y3VybC83Ljc0LjA=',rm: 'R0VU',d: 'MwkEwtnLRdY55hAYdJZBy39JGlB1ZUI3Qa/AqWJrjo8VC340X2o/9bxmmMqRTltGgAmHaVXwlCUkx7cYR4N3RRq0pFlBlbtzOmHm0hQa9JbGvnaLg84/A6Mj7BS9jYDEligktKIhQXuQ0IioBiszny7ns44bwe5nuJCZd+ApD3E33ZXvmXrjvNWsmO2qi+KSBgx/lahqE3db42TQAdpvttozLr6Aet5jkHJaPskcHurWV8xDAdy/XcudJDJCkYr0Ga+WZE9Nghe4CE5Ef+ap03wGwrfslzzkum9LCvGiCFaXMGe7lBcuQyFIrhBLXx8kfTgmVgWEfHTUswJQvl4bEWnN7AngAztqCLvFl+BKzitXlTKwMK5+nKbR/s9gwhGXD1oPP9j8n4mmUm1c+4VYDTMyN8ihJ/oidgZUK0KetQ4ZeODhTaG3gJMUh5aqLaAn4DmTmALrP2RXsibuPT8uJ9aMdd9cvcGzFVUeHDs3yYHuy8+ZwtI8vYK+S4PV7IDA',t: 'MTY5MTMzNzQ0MS4xNjQwMDA=',cT: Math.floor(Date.now() / 1000),m: '+IM59jul8m9IY3aPDZu4dPdxG9p4/ROJoQHCjp6RqK4=',i1: 'xX3ECaEB6Ch2BQfky5UMgQ==',i2: '4BkugZHlc0VgjtarqFhv8g==',zh: 'cZPSqsDJGBrnbnxrQfo4BS0PIpgb+qtDvibTuMIMn5E=',uh: 'zu+cQgicc5rF6Q8HHTJhdGCD3QVkjetpkn+QXGMpZBU=',hh: 'ZOyUzfV2lj4ypzUqyT4vj6ME3qJ5M3kJUzdu55dzo24=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=7f28799f4bf71227';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/client\/raspberry-pi?__cf_chl_rt_tk=yrAdWPgKjnx7BU8qGlRGnYRvk3GsN6jTp1..FnY5.K8-1691337441-0-gaNycGzNCrs" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);};}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>'

**Comment by rnayabed** [comment]
Use the url ` https://raw.githubusercontent.com/stream-pi/scripts/master/client-install-raspberry-pi.sh ` instead of `https://install.stream-pi.com/client/raspberry-pi`

**Comment by rnayabed** [comment]
Will fix this soon

**Comment by rnayabed** [comment]
should be fixed now. please notify if it fails again
